name: Build and Deploy
on: 
  push:
    branches: main
    paths: ["docs-build/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-storybook
      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync . s3://storybook